### ISSUE TITLE
Crash on startup with Fabric API 0.60.0

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [stauplays/Arclight-Fabric#2]
I'm using Quilt, but the issue is the same on Fabric due to this commit, which removed `SpawnRestrictionAccessor`: https://github.com/FabricMC/fabric/commit/42d99c329d68ca8ba9e4b7fd2819635e49f765d9

```shell
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'arclight'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:63)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:61)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:46)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/mixin/object/builder/SpawnRestrictionAccessor
	at net.verox.arclight.world.feature.mob.ModEntitySpawn.addEntitySpawn(ModEntitySpawn.java:17)
	at net.verox.arclight.world.ModWorldGen.generateModWorldGen(ModWorldGen.java:12)
	at net.verox.arclight.ArclightMod.onInitialize(ArclightMod.java:27)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$0(Hooks.java:52)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59)
	... 18 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.mixin.object.builder.SpawnRestrictionAccessor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:159)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 24 more
```

**Comment by Footage2-Amply-Pounce** [comment]
Fixed.
